Repository ikke6992/specops, pull requests merged in 2024-03, with the labels that each got.

#57 Bugfix duplicate tasks
  backend/src/main/java/nl/itvitae/specops/tasks/TaskController.java
Labels: bug

#68 67 feature request suggestion make progress bars dynamic
  backend/src/main/java/nl/itvitae/specops/Seeder.java
  frontend/src/components/common/cards/card1/Card1.tsx
  frontend/src/components/common/cards/card1/Card1CompleteButton.tsx
  frontend/src/components/common/cards/card1/Card1Status.tsx
Labels: feature

#76 Bug fixing and UI redesign
  backend/src/main/java/nl/itvitae/specops/tasks/TaskController.java
  backend/src/main/java/nl/itvitae/specops/users/User.java
  backend/src/main/java/nl/itvitae/specops/users/UserService.java
  frontend/src/components/common/buttons/FunctionButton.tsx
  frontend/src/components/common/buttons/NavigateButton.tsx
  frontend/src/components/common/cards/card1/Card1.tsx
  frontend/src/components/common/cards/card1/Card1CompleteButton.tsx
  frontend/src/components/common/cards/card1/Card1Dates.tsx
  frontend/src/components/common/cards/card1/Card1Status.tsx
  frontend/src/components/common/filter/FilterTabs.tsx
  frontend/src/components/common/filter/Tab.tsx
  frontend/src/components/common/filter/TaskTabs.tsx
  frontend/src/components/common/layout/Layout.tsx
  frontend/src/components/common/log/Log.tsx
  frontend/src/components/common/log/LogData.tsx
  frontend/src/components/common/log/LogHead.tsx
  frontend/src/components/common/modal/Modal.tsx
  frontend/src/components/common/modal/ModalClose.tsx
  frontend/src/components/common/modal/ModalDeactivate.tsx
  frontend/src/components/common/modal/ModalSubmit.tsx
  frontend/src/components/manage-history/Content.tsx
  frontend/src/components/manage-history/HistoryManager.tsx
  frontend/src/components/manage-tasks/TaskCreator.tsx
  frontend/src/components/manage-tasks/TaskEditor.tsx
  frontend/src/components/manage-tasks/TaskList.tsx
  frontend/src/components/manage-tasks/TaskManager.tsx
  frontend/src/components/manage-tasks/TaskManagerButtons.tsx
  frontend/src/components/manage-tasks/fields/DeadlineField.tsx
  frontend/src/components/manage-tasks/fields/DepartmentField.tsx
  frontend/src/components/manage-tasks/fields/FieldCombination.tsx
  frontend/src/components/manage-tasks/fields/IntervalField.tsx
  frontend/src/components/manage-tasks/fields/NameField.tsx
  frontend/src/components/manage-tasks/fields/TimeframeField.tsx
  frontend/src/contexts/HistoryContext.tsx
  frontend/src/contexts/TaskContext.tsx
  frontend/src/main.tsx
  frontend/tailwind.config.js
Labels: bug, feature, management, history, filter & search
